const clubs = [
  { 
    id: 'c1',
    label: '🃑',
    value: 1,
    suite: 'clubs',
    color: 'black',
    isFaceUp: false,
    suiteSymbol: '♣︎',
  },
  { 
    id: 'c13',
    label: '🃞',
    value: 13,
    suite: 'clubs',
    color: 'black',
    isFaceUp: false,
    suiteSymbol: '♣︎',
  },
  { 
    id: 'c12',
    label: '🃝',
    value: 12,
    suite: 'clubs',
    color: 'black',
    isFaceUp: false,
    suiteSymbol: '♣︎',
  },
  { 
    id: 'c11',
    label: '🃛',
    value: 11,
    suite: 'clubs',
    color: 'black',
    isFaceUp: false,
    suiteSymbol: '♣︎',
  },
  { 
    id: 'c10',
    label: '🃚',
    value: 10,
    suite: 'clubs',
    color: 'black',
    isFaceUp: false,
    suiteSymbol: '♣︎',
  },
  { 
    id: 'c9',
    label: '🃙',
    value: 9,
    suite: 'clubs',
    color: 'black',
    isFaceUp: false,
    suiteSymbol: '♣︎',
  },
  { 
    id: 'c8',
    label: '🃘',
    value: 8,
    suite: 'clubs',
    color: 'black',
    isFaceUp: false,
    suiteSymbol: '♣︎',
  },
  { 
    id: 'c7',
    label: '🃗',
    value: 7,
    suite: 'clubs',
    color: 'black',
    isFaceUp: false,
    suiteSymbol: '♣︎',
  },
  { 
    id: 'c6',
    label: '🃖',
    value: 6,
    suite: 'clubs',
    color: 'black',
    isFaceUp: false,
    suiteSymbol: '♣︎',
  },
  { 
    id: 'c5',
    label: '🃕',
    value: 5,
    suite: 'clubs',
    color: 'black',
    isFaceUp: false,
    suiteSymbol: '♣︎',
  },
  { 
    id: 'c4',
    label: '🃔',
    value: 4,
    suite: 'clubs',
    color: 'black',
    isFaceUp: false,
    suiteSymbol: '♣︎',
  },
  { 
    id: 'c3',
    label: '🃓',
    value: 3,
    suite: 'clubs',
    color: 'black',
    isFaceUp: false,
    suiteSymbol: '♣︎',
  },
  { 
    id: 'c2',
    label: '🃒',
    value: 2,
    suite: 'clubs',
    color: 'black',
    isFaceUp: false,
    suiteSymbol: '♣︎',
  }
];

export default clubs;