const diamonds = [
  { 
    id: 'd1',
    label: '🃁',
    value: 1,
    suite: 'diamonds',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♦︎',
  },
  { 
    id: 'd13',
    label: '🃎',
    value: 13,
    suite: 'diamonds',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♦︎',
  },
  { 
    id: 'd12',
    label: '🃍',
    value: 12,
    suite: 'diamonds',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♦︎',
  },
  { 
    id: 'd11',
    label: '🃋',
    value: 11,
    suite: 'diamonds',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♦︎',
  },
  { 
    id: 'd10',
    label: '🃊',
    value: 10,
    suite: 'diamonds',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♦︎',
  },
  { 
    id: 'd9',
    label: '🃉',
    value: 9,
    suite: 'diamonds',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♦︎',
  },
  { 
    id: 'd8',
    label: '🃈',
    value: 8,
    suite: 'diamonds',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♦︎',
  },
  { 
    id: 'd7',
    label: '🃇',
    value: 7,
    suite: 'diamonds',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♦︎',
  },
  { 
    id: 'd6',
    label: '🃆',
    value: 6,
    suite: 'diamonds',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♦︎',
  },
  { 
    id: 'd5',
    label: '🃅',
    value: 5,
    suite: 'diamonds',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♦︎',
  },
  { 
    id: 'd4',
    label: '🃄',
    value: 4,
    suite: 'diamonds',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♦︎',
  },
  { 
    id: 'd3',
    label: '🃃',
    value: 3,
    suite: 'diamonds',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♦︎',
  },
  { 
    id: 'd2',
    label: '🃂',
    value: 2,
    suite: 'diamonds',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♦︎',
  },
];

export default diamonds;