const hearts = [
  {
    id: 'h1',
    label: '🂱',
    value: 1,
    suite: 'hearts',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♥︎',
  },
  {
    id: 'h13',
    label: '🂾',
    value: 13,
    suite: 'hearts',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♥︎',
  },
  {
    id: 'h12',
    label: '🂽',
    value: 12,
    suite: 'hearts',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♥︎',
  },
  {
    id: 'h11',
    label: '🂻',
    value: 11,
    suite: 'hearts',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♥︎',
  },
  {
    id: 'h10',
    label: '🂺',
    value: 10,
    suite: 'hearts',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♥︎',
  },
  {
    id: 'h9',
    label: '🂹',
    value: 9,
    suite: 'hearts',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♥︎',
  },
  {
    id: 'h8',
    label: '🂸',
    value: 8,
    suite: 'hearts',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♥︎',
  },
  {
    id: 'h7',
    label: '🂷',
    value: 7,
    suite: 'hearts',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♥︎',
  },
  {
    id: 'h6',
    label: '🂶',
    value: 6,
    suite: 'hearts',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♥︎',
  },
  {
    id: 'h5',
    label: '🂵',
    value: 5,
    suite: 'hearts',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♥︎',
  },
  {
    id: 'h4',
    label: '🂴',
    value: 4,
    suite: 'hearts',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♥︎',
  },
  {
    id: 'h3',
    label: '🂳',
    value: 3,
    suite: 'hearts',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♥︎',
  },
  {
    id: 'h2',
    label: '🂲',
    value: 2,
    suite: 'hearts',
    color: 'red',
    isFaceUp: false,
    suiteSymbol: '♥︎',
  },
];

export default hearts;